In [9]:
import robotic as ry
import numpy as np

### PART A

In [10]:
C = ry.Config()

C.addFile(ry.raiPath("../rai-robotModels/objects/kitchen.g"))


In [11]:
C.view()

0

In [12]:
hammer_handle = C.addFrame(name="hammer_handle", parent="sink1")
hammer_handle.setShape(ry.ST.ssBox, size=[0.3, 0.05, 0.03, 0.005])
hammer_handle.setRelativePosition([0.1, 0.1, 0.415])
hammer_handle.setColor([0.65, 0.50, 0.39])



In [13]:
hammer_head = C.addFrame(name="hammer_head", parent="hammer_handle")
hammer_head.setShape(ry.ST.ssBox, size=[0.1, 0.05, 0.03, 0.005])
hammer_head.setRelativePosition([0.125, 0.0, 0.0])
hammer_head.setColor([0.55, 0.57, 0.58])
hammer_head.setQuaternion([1, 0, 0.0, 1])


In [14]:
C.view()

0

In [22]:
mug = C.addFrame(name="mug", parent="sink1")
mug.setShape(ry.ST.ssBox, size=[0.05, 0.05, 0.2, .01])
mug.setRelativePosition([-0.1, -0.1, 0.5])
mug.setColor([0.2, 0.2, 0.2])

In [23]:
C.view()

0

In [53]:
print(hammer_handle.getPosition())
print(hammer_handle.getQuaternion()) # Part A

[ 1.9   -0.08   0.835]
[0.32599068 0.         0.         0.94537298]


### PART B 

In [24]:
tray = C.addFrame(name="tray", parent="stove1")
tray.setShape(ry.ST.ssBox, size= [0.2, 0.2, 0.05, 0.02])
tray.setRelativePosition([0.0, 0.0, 0.42])
tray.setColor([0.0, 1.0, 0.0])
tray.setQuaternion([1, 0, 0.0, 0.5])

-- WARNING:kin.cpp:addFrame:193(-1) frame already exists! returning existing without modifications!


In [25]:
C.view()

0

### PART C

### State 1

In [26]:
tray.setShape(ry.ST.ssBox, size= [0.4, 0.4, 0.05, 0.02])


In [27]:
tray.getPosition()

array([0.5 , 2.  , 0.82])

In [28]:
mug.setPosition([0.5, 1.9, .94])

In [29]:
C.view()

0

In [17]:
hammer_handle.setPosition([0.5 , 2.  , 0.86])
hammer_head.setRelativePosition([0.125, 0.0, 0.0])


In [30]:
C.view()

0

In [31]:
hammer_handle.setRelativeQuaternion([1, 0, 0.0, 0.5])


In [32]:
C.view()

0

### State 2

In [33]:
C.getFrame("table1").getPosition()

array([2.   , 0.   , 0.385])

In [34]:
tray.setPosition([2.   , 0.   , 0.385*2 + tray.getSize()[2]*0.5])

In [35]:
tray.getSize()

array([0.4 , 0.4 , 0.05, 0.02])

In [36]:
C.view()

0

In [25]:
mug.setPosition([2.1   , 0.   , 0.385*2 + tray.getSize()[2] + mug.getSize()[2]*0.5])

In [37]:
C.view()



0

In [27]:
mug.getSize()

array([0.05, 0.05, 0.2 , 0.01])

In [38]:
hammer_handle.setPosition([1.9 , -0.08  , 0.385*2 + tray.getSize()[2] + hammer_handle.getSize()[2]*0.5])
hammer_handle.setRelativeQuaternion([1, 0, 0.0, 2.9])


In [39]:
C.view()

0

In [30]:
mug.getRelativePosition() #PART D

array([ 2.6 , -2.  ,  0.52])

### Two Link Manipulator (Part 2)

In [46]:
K = ry.Config()
K.addFile("two_link_manipulator.g")
K.view()

0

### PART B

In [49]:
target = K.getFrame("target")
joint_angles = 2*np.pi * np.random.rand(3)


def forward_kinematics(q):
    q0 = -q[0]
    q1 = -q[1]
    y1 = -np.sin(q0)
    z1 = np.cos(q0)
    
    y2 = -np.sin(q1)
    z2 = np.cos(q1)
    y1 = y1 + np.cos(q0)*y2 - np.sin(q0)*z2
    z1 = z1 + np.sin(q0)*y2 + np.cos(q0)*z2
    
    return np.array([0,y1,z1])

pos_target = forward_kinematics(joint_angles)

target.setPosition(pos_target)
K.setJointState(joint_angles)

K.view()

q = np.zeros(K.getJointDimension())
K.setJointState(q)
target.setPosition([0,0,0])

### PART C 

In [50]:
def Jacobian(q):
    q0 = q[0]
    q1 = q[1]
    y_q0 = -np.cos(q0) + np.sin(q0) * np.sin(q1) - np.cos(q0) * np.cos(q1)
    y_q1 = -np.cos(q0) * np.cos(q1) + np.sin(q0) * np.sin(q1)
    z_q0 = -np.sin(q0) -np.cos(q0) * np.sin(q1) - np.sin(q0) * np.cos(q1)
    z_q1 = -np.sin(q0) * np.cos(q1) - np.cos(q0) * np.sin(q1)
    return np.array([[y_q0, y_q1],[z_q0, z_q1]])

In [51]:
joint_angles = [1.95205226, 3.15753276, 0]
J = Jacobian(joint_angles)
print(J)

[[-0.01474768 -0.3868342 ]
 [-0.00604877  0.92214929]]


### PART 4

In [2]:
CR = ry.Config()
CR.addFile("maze.g")
CR.addFile("cargo.g")
CR.addFile("cargobot.g")


In [3]:
CR.view()

0

In [3]:
S = ry.Skeleton()



In [4]:
cp11 = CR.addFrame("cp11")
cp11.setShape(type = ry.ST.marker, size = [0.3])                  
cp11.setPosition([0, -3, 0.48])

cp21 = CR.addFrame("cp21")
cp21.setShape(type = ry.ST.marker, size = [0.3])                  
cp21.setPosition([4, 3, 0.48])

cp22 = CR.addFrame("cp22")
cp22.setShape(type = ry.ST.marker, size = [0.3])                  
cp22.setPosition([-2, -3, 0.48])

In [7]:
#S.addEntry([1.], ry.SY.topBoxGrasp, ["l_gripper", "cargo_handle"])

S.addEntry([1., 1.], ry.SY.touch,  ["l_gripper", "cargo_handle"])
S.addEntry([1., 1.5], ry.SY.stable, ["l_gripper", "cargo_handle"])
S.addEntry([2.5, 3], ry.SY.positionEq, ["base", "cp11"])

S.addEntry([3.5, 4], ry.SY.positionEq, ["base", "cp1"])

S.addEntry([4.5, 5], ry.SY.positionEq, ["base", "cp21"])

S.addEntry([5.5, 6], ry.SY.positionEq, ["base", "cp2"])

S.addEntry([6.5, 7], ry.SY.positionEq, ["base", "cp22"])

S.addEntry([7.5, 8], ry.SY.positionEq, ["base", "final"])

S.addEntry([8, 10.5], ry.SY.poseEq, ["cargo", "goal_area"])

#S.addEntry([0.8, 1.2], ry.SY.downUp, ["l_gripper"])
#S.addEntry([1.8, 2.2], ry.SY.downUp, ["l_gripper"])#
S.enableAccumulatedCollisions(False)

lenScale, homingScale, and collScale are parameters that are likely used for some kind of optimization or cost function. Here's a brief explanation of each:

lenScale (Length Scale): This parameter is likely used to control the relative importance of the length or distance-related terms in the optimization. A higher value would mean that length-related terms have more influence on the optimization, while a lower value would reduce their impact.

homingScale (Homing Scale): This parameter might be related to a "homing" behavior, which typically means returning to a specific position or configuration. It could control how strongly the algorithm prioritizes returning to a specific home position.

collScale (Collision Scale): This parameter likely controls how much the optimization considers avoiding collisions. A higher value would mean that avoiding collisions is more important, while a lower value would reduce its importance.

In [8]:
## solve for waypoints: create a komo instance, create nlp instance, then call generic solver

komo = S.getKomo_path(CR, stepsPerPhase=30, accScale=1e0, lenScale=1e-3, homingScale=0, collScale=1e0)

ret = ry.NLP_Solver(komo.nlp(), verbose=0 ) .solve() ## WHAT IS NLP!! SOLVER?
print(ret)
q = komo.getPath();
print('size of path:', q.shape)

komo.view(False, "result")
komo.view_play(True, .5)


{ time: 1.07812, evals: 115, done: 1, feasible: 0, sos: 83.2729, f: 0, ineq: 0, eq: 7680.02 }
size of path: (315, 10)


True